### ISSUE TITLE
QueryFailedError: SQLITE_ERROR: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint

### ISSUE THREAD

**Issue by drauber** [deadlinecode/baileys-bottle#16] opened 2023-02-08 16:51 UTC
**Describe the bug**
Randomly the erros is showed on Baileys Logs.

**To Reproduce**
I can't reproduce it.
The has only null values, this is not normal.
INSERT INTO "chat"("DBId", "id", "messages", "newJid", "oldJid", "lastMsgTimestamp", "unreadCount", "readOnly", "endOfHistoryTransfer", "ephemeralExpiration", "ephemeralSettingTimestamp", "endOfHistoryTransferType", "conversationTimestamp", "name", "pHash", "notSpam", "archived", "disappearingMode", "unreadMentionCount", "markedAsUnread", "participant", "tcToken", "tcTokenTimestamp", "contactPrimaryIdentityKey", "pinned", "muteEndTime", "wallpaper", "mediaVisibility", "tcTokenSenderTimestamp", "suspended", "terminated", "createdAt", "createdBy", "description", "support", "isParentGroup", "isDefaultSubgroup", "parentGroupId", "displayName", "pnJid", "selfMasked", "mute", "pin", "archive", "dBAuthId") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1) ON CONFLICT ( "id", "dBAuthId" ) DO UPDATE SET "id" = EXCLUDED."id", "dBAuthId" = EXCLUDED."dBAuthId"

**Expected behavior**
The error log does not show any errors.

**Screenshots**
![Error_Bottle](https://user-images.githubusercontent.com/4416953/217596035-6c2b0612-966d-4422-a64a-0b3343428f59.png)

**Version (please complete the following information):**
 - NodeJS: v16.17.0
 - Baileys: 5.0.0
 - Baileys-bottle: 2.0.0

**Additional context**
Maybe, this is not related, but i'm losting messages (not received by Baileys or not sending to recipients)

**Comment by deadlinecode** [comment] 2023-02-09 13:29
Yeah i've had this bevore with nulls
Will need to investigate a bit more :/

**Comment by PauloAK** [comment] 2023-02-16 00:34
Having that same issue randomly as well :/
Will investigate as well when I've some time.

**Comment by ju-li** [comment] 2023-03-01 07:07
I'm getting this error and the way to reproduce it is to create a group chat.

When a group chat is created, these 3 events are emitted: `groups.upsert`, `chats.upsert`, and `messages.upsert`

The `groups.upsert` and `messages.upsert` events seem to be handled correctly. The events' data show up in the `groups_metadata` and `messages` tables correctly.

So the error should be coming from how the `chats.upsert` event is handled. I've no idea what about it is causing the error, though.

Hope this helps

**Comment by ahmedRSA** [comment] 2023-03-20 07:18
is there any fix for this? 
**package is completely useless if this doesn't gets fixed.**

**Comment by deadlinecode** [comment] 2023-03-22 20:25
I think i will have to sort out null values since wa seems to emit those on the event but dbs are not happy with null values especially when upserting (which is kinda odd since it should then just insert but nvm)
I will just try catch for now and get to it asap

**Comment by deadlinecode** [comment] 2023-03-22 20:39
@drauber @ahmedRSA @PauloAK @ju-li 
I fucked up while mapping the newChat parameter
Should be fixed in [the newest hot fix release](https://www.npmjs.com/package/baileys-bottle/v/2.1.1) (https://www.npmjs.com/package/baileys-bottle/v/2.1.1)

I also added a try catch just for safety
Please reopen if it still failes

**Closed by deadlinecode** 2023-03-22 20:39 UTC
Labels: bug
